### ISSUE TITLE
Improve nav-bar

### ISSUE THREAD

**Issue by rdhillon1016** [social-media-app-project/social-media-app#14]
- [x] Since there's only three options on the nav-bar, probably best to lay it horizontally at the top of the page instead of the left side (so much dead space on the left side)
- [x] This will change the location of the logout button, can probably throw that on the top as well (in total, 4 buttons at the top)

**Comment by brandhawa99** [comment]
Probably a good idea to leave it on the side so that it is sticky and user has access to the menu items no matter how far they scroll /maybe have it move to the top on mobile view

**Comment by rdhillon1016** [comment]
Sounds good
