### ISSUE TITLE
Investigate using TLS for client-server communication

### ISSUE THREAD

**Issue by rdhillon1016** [social-media-app-project/social-media-app#32]
- [ ] Find out how hard it is to get a TLS certificate

**Comment by brandhawa99** [comment]
when you host it they just give you one

**Comment by brandhawa99** [comment]
backend and frontend

**Comment by rdhillon1016** [comment]
> when you host it they just give you one

Host on what and where does it say that

**Comment by brandhawa99** [comment]
im talking about heroku https://devcenter.heroku.com/articles/ssl but all cloud platforms do it

**Comment by rdhillon1016** [comment]
Sounds good. Closing issue and creating new one to use HTTPS when deployment-ready.
