### ISSUE TITLE
Set up endpoints for posts

### ISSUE THREAD

**Issue by rdhillon1016** [social-media-app-project/social-media-app#33]
- [ ] Ability to get the most recent x posts from you/your friends (pagination to get more)
- [ ] Ability to get the oldest x comments on a single post (pagination to get more)
- [ ] Ability to get the most recent x posts from a single user
- [ ] Delete a post if authorized
- [ ] Like a post if authorized
- [ ] Comment on a post if authorized

Can be unauthenticated for now, until #30 is done

**Comment by brandhawa99** [comment]
are people without accounts able to see posts

**Comment by rdhillon1016** [comment]
> are people without accounts able to see posts

I would say yes for now.

In Twitter you can, Facebook you can't
