### ISSUE TITLE
Media queries to make Home Feed more mobile-friendly

### ISSUE THREAD

**Issue by rdhillon1016** [social-media-app-project/social-media-app#58]
- Some/all of the text and buttons could be smaller
- Some of the padding looks weird in mobile view (e.g the padding between the user's name and the date label)
- Change nav-bar to the top horizontally on mobile view

**Comment by brandhawa99** [comment]
made nav bar at the bottom so its easier to reach

**Comment by brandhawa99** [comment]
is the padding too much or too little
